services:
  - type: web
    name: ai-detector-backend
    env: python
    buildCommand: ./build.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CARGO_HOME
        value: /tmp/cargo
      - key: CARGO_TARGET_DIR
        value: /tmp/cargo-target
      - key: CARGO_BUILD_TARGET_DIR
        value: /tmp/cargo-target
      - key: RUST_BACKTRACE
        value: "1"
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: POSTGRES_SERVER
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_DB
        sync: false
      - key: POSTGRES_PORT
        value: "5432"
      - key: BACKEND_CORS_ORIGINS_STR
        sync: false
